### ISSUE TITLE
Next Collaboration Summit - May 4-5 2017, Berlin

### ISSUE THREAD

**Issue by joshgav** [nodejs/summit#39] opened 2016-12-08 22:23 UTC
The days together in Austin, both at the conference and in the Summit afterwards, were IMO great at helping us reach consensus on some issues, review current and recent work, and make some short-term plans; not to mention strengthen our personal relationships! 🍻  Although we communicate informally in many ways, I think it may be good for us to hold "official" Collaboration Summits more than once per year. @nodejs/collaborators what do you think?

When and where might we hold the next Collaboration Summit? Perhaps alongside a conference in the spring or summer?

EDIT:
**Confirmed!** May 4-5 2017, Berlin
<sup>-Wm</sup>
Location: http://co-up.de/ ([google maps](https://www.google.com/maps?hl=en&q=co-up+berlin)).

/cc @mikeal @nodejs/tsc

**Comment by TheAlphaNerd** [comment] 2016-12-08 22:30
There have been talks about an event in Japan in April. Without going into to many details regarding that event, as it is not yet confirmed, I do think that it would be interesting to offer a summit (and code and learn) in another part of the world

**Comment by mcollina** [comment] 2016-12-08 22:48
There are several possible events to be attached on, including jsconfeu in May.

**Comment by mikeal** [comment] 2016-12-08 22:52
@mcollina Great Suggestion! I'm going to be there but I just hadn't thought of pairing up with that one yet :)

**Comment by bnoordhuis** [comment] 2016-12-08 23:14
jsconf.eu at EUR 700 for a ticket is outrageously expensive, though.  Maybe not a big deal for people with corporate sponsorship but for everyone else it's pretty steep.

**Comment by mikeal** [comment] 2016-12-08 23:41
@bnoordhuis the summit would be detached from JSConf.eu so people attending the summit wouldn't need a JSConf ticket. The foundation would fit the bill for the venue and catering, we'd just be doing it the same week as JSConf so that people who were already traveling into Berlin for it could easily extend their trip to attend.

**Comment by claudiorodriguez** [comment] 2016-12-09 09:33
jsconf.eu sounds extremely convenient, but then again I am based in Europe and was already planning to attend, so I might be a bit biased

**Comment by indutny** [comment] 2016-12-09 09:55
How about doing it in Moscow eventually?

**Comment by seishun** [comment] 2016-12-09 10:11
Moscow is a suboptimal choice logistically since most collaborators would need a visa to go there.

**Comment by indutny** [comment] 2016-12-09 10:14
Welcome to my world :) I need to get visa to practically every place except Russia and USA.

**Comment by vkurchatkin** [comment] 2016-12-09 15:42
> How about doing it in Moscow eventually?

Oh, I'm in! 😀

**Comment by benjamingr** [comment] 2016-12-09 16:06
If it's in Berlin I probably wouldn't mind paying for the flight as it's pretty close (~$200) and would love to attend.

**Comment by ChALkeR** [comment] 2016-12-09 17:37
I would be glad to attend this meeting (given that it would happen in 2017) =).

**Comment by seishun** [comment] 2016-12-09 17:45
@ChALkeR no matter where it's held?

**Comment by jbergstroem** [comment] 2016-12-09 18:58
Going to make an effort for this meeting as well. Both Japan and Europe sounds like fun.

**Comment by mikeal** [comment] 2016-12-09 19:07
This shouldn't be a thread about fun places to visit :)

We are trying to co-locate with an event that is already drawing a lot of our contributors in order to reduce costs and maximize the number of contributors at the event.

From experience, JSConf.eu pulls a lot of people in from all over Europe. While I have thoroughly enjoyed all my trips to Japan for NodeFest, it tends to pull in a local audience more than an international audience. That doesn't mean we can'd do something great in Japan alongside one of their events, but something like Code & Learn is probably more fitting than a Collab Summit :)

Being that the last event was in the US I'd definitely like to see the next one located somewhere else to lower the barrier for our international contributors but we need to be strategic in where we put it in order to maximize participants and reduce costs.

**Comment by ChALkeR** [comment] 2016-12-09 19:09
@seishun I think that travel+entrance+hotel prices would be the limiting factor for me in some of the cases, as I don't have corporate sponsorship, also I would like to avoid some places (but I don't think that we would have a conference in those).

**Comment by jbergstroem** [comment] 2016-12-09 21:41
@mikeal sorry for the poor choice of wording, but I think it was good that you elaborated on rationale for choosing location. My comment was mostly about being able to do both locations.

**Comment by mikeal** [comment] 2016-12-09 22:46
@jbergstroem I didn't mean for that to be directed at you, the whole thread was going in that direction :)

**Comment by mikeal** [comment] 2016-12-09 22:47
@ChALkeR the foundation has travel stipends you can apply for.

**Comment by ChALkeR** [comment] 2016-12-09 23:22
@mikeal Thanks, I will take that into an account (in fact, I was aware of that, but the reason why I didn't travel to conferences in 2016 was not financial). The main point of my previous message was that I would try to attend conferences in 2017 (unlike 2016), given that it would be feasable from the financial side (with or without travel stipends). It doesn't _have_ to be in Moscow for that (though I would definitely attend an event in Moscow) =).

**Comment by ronkorving** [comment] 2016-12-12 02:39
For me, not joining is mainly financially driven. If one were to be hosted in Japan, definitely count me in :)

**Comment by seishun** [comment] 2017-02-08 10:10
@MylesBorins have there been any news about the event in Japan? Are the talks still ongoing?

**Comment by mcollina** [comment] 2017-02-08 11:06
To the best of my knowledge, the event in Japan is not happening.

We still need to start planning if we want a collaborator summit to happen in May/June, or flying people around is going to be costly.

**Comment by targos** [comment] 2017-02-08 11:47
I hope we can do something in Berlin during JSConf EU.

**Comment by MylesBorins** [comment] 2017-02-08 15:54
+1 to trying to arrange something in Berlin

**Comment by mcollina** [comment] 2017-02-08 15:56
The possibilities are the 4th and 5th or the 8th and 9th of May.

**Comment by eljefedelrodeodeljefe** [comment] 2017-02-08 15:57
Since I am living in Berlin I am happy to support with organising, logistically or even financially. Just let me know.

**Comment by addaleax** [comment] 2017-02-15 16:55
Who would be the group of people deciding whether we do this or not? @nodejs/tsc? I’m adding the label but feel free to modify that if I’m mistaken…

Also /cc @williamkapke because he probably knows the actual answer to that question

**Comment by williamkapke** [comment] 2017-02-15 17:42
@addaleax yup- the TSC would propose it to the Board and get final approval.

**Comment by addaleax** [comment] 2017-02-20 12:41
Ok, given that, as @mcollina mentioned above, there are really two dates for an event around JSConf EU that make the most sense, maybe we should we have a quick poll to see what collaborators would prefer?

@nodejs/collaborators: Could you please
* :smile: this comment if you would be able to be at a summit on May 4th/5th
* :tada: this comment if you would be able to be at a summit on May 8th/9th
? :)

**Comment by MylesBorins** [comment] 2017-02-22 22:52
Have we looked into available spaces for this? The dates may be limited by this

**Comment by addaleax** [comment] 2017-02-22 22:55
I don’t think so (and, like, my little poll wasn’t intended to be a definitive vote for the date). If we’d really only going to be on the order of 10 people (and still decide to do it) finding a space should be pretty easy…

**Comment by mikeal** [comment] 2017-02-22 22:56
@MylesBorins I put out a call on twitter but didn't hear back yet, I'm going to poke some people individually next.

**Comment by mikeal** [comment] 2017-02-23 17:53
I've just been talking to @janl and he thinks co-up could work. 

Co-up is a great space, I've been there many times and is one of the focal points of the Berlin open source and JS scene :)

**Comment by addaleax** [comment] 2017-02-25 21:10
We talked about this a bit in this week’s TSC meeting, and right now it would be good to see some suggestions for concrete issues that we should discuss, so that we can estimate whether a one-day or two-day summit makes the most sense.

/cc @nodejs/collaborators feel free to brainstorm!

**Comment by mcollina** [comment] 2017-02-25 22:11
@addaleax I'd phrase it another terms: do we want to do a "Code & Learn" as well or not?

**Comment by addaleax** [comment] 2017-02-25 23:10
> do we want to do a "Code & Learn" as well or not?

I know that would not be included in the 2017 budget plans for Code & Learn, so – and @hackygolucky or @mikeal, correct me if I’m wrong – I think that can be answered as something we won’t do?

**Comment by joshgav** [comment] 2017-02-27 16:40
@mcollina @addaleax I've been thinking that "Code & Learn" and "Collaborators' Summit" are similar concepts at heart which happen to manifest differently because they target different audiences. That is, both "Code & Learn" and "Collaboration Summit" bring together a bunch of developers and architects to discuss, contribute to and enhance Node core; Collab Summits just happen to attract those of us who've had a bit more experience and time here, and maybe come in with work items to discuss.

With that in mind, perhaps **as part of Code & Learn** we should offer additional domains at a deeper depth for more experienced contributors, as a form of Collaboration Summit. For example, I could spend an hour discussing Diagnostics projects and needed work, such as [Trace Controller][] and [Inspector][], and a group could hack on and discuss these items for a couple days. That group could include members of the Diag WG if/when feasible.

[Trace Controller]: https://github.com/nodejs/diagnostics/issues/84
[Inspector]: https://github.com/nodejs/node/issues/11421

**Comment by nebrius** [comment] 2017-02-27 18:17
It might be useful to discuss the community committee more. Since it's still in its infancy, there's lots to be done. It does depend on how many of the community committee members will be in attendance (there's not many of us). cc @hackygolucky.

**Comment by hackygolucky** [comment] 2017-02-27 20:47
Ah, so is this happening around the time of JSConfEU? I didn't realize the discussions were that far along. @nebrius ah, it's a super busy time of year for me, but I can make sure I'm there if I need to be for this(was on the side of attending JSConfEU anyway for advocacy work). I would loooove to have more people from the Collaborators group participating in the CommComm discussions!

@addaleax Yeah, we didn't budget for a Code & Learn attached to a spring Collab Summit. Doesn't mean it couldn't happen. It just wouldn't have budget to support travel/space/food&bev but that just means a more DIY approach if y'all would like to. The travel for y'all would already be covered from the TSC travel fund anyway for Collab Summit, right?

**Comment by Trott** [comment] 2017-02-27 22:02
Two more options, which are not mutually exclusive: 

* We could do a smaller/quieter/unfunded Code & Learn (and just call it NodeTodo if the Foundation doesn't want to do small quiet things).

* Instead or even at the same time, maybe spend some time working on clearing out the backlog of pull requests and issues on the project. Seriously, if we could close 50 old PRs and 50 old issues, that would be huge. I think it is discouraging for both the people who contributed the PRs and issues as well as discouraging to others to see large numbers of open PRs/issues that are basically perpetually ignored.

**Comment by hackygolucky** [comment] 2017-02-28 04:20
Awesome ideas @trott!

And I didn't mean to imply that unfunded code & learns are a no no(not my
call anyway! It's a core thing afaik). They have happened and happen fine
without allocation. I just meant to be clear that a current allocation
doesn't exist. I could also request one, if interest is there.

**Comment by MylesBorins** [comment] 2017-03-01 19:28
Hey all... I don't want to be that human but I think we need to settle on a day.  Are we doing one day or two days.

It is started to make sense to me to run this before jsconf as people will already be around

**Comment by MylesBorins** [comment] 2017-03-01 20:28
Also want to mention that quite a bit of the V8 team is going to be in town on the Friday before JSConf.

As such I would like to push that we move forward with running the summit the 4th and 5th. I also think that we should plan a node + V8 dinner for the evening of the 5th.

**Comment by hackygolucky** [comment] 2017-03-08 00:06
I agree @mylesborins. So does May 4th and 5th work for enough people? Something to vote on in the next TSC meeting?

Let me know if y'all want any kind of help coordinating. I'm still having to figure out whether I can make it, but we def got feedback after the last one. I'll make a separate issue about the Fall summit.

**Comment by jasnell** [comment] 2017-03-08 00:08
If we can get a good number of contributors present then definite +1. We should look at having a more organized agenda than the last couple we had.

**Comment by addaleax** [comment] 2017-03-08 00:11
Yeah, I think we’re pretty much settled on May 4th + 5th. It’s on the TSC agenda, so I guess there’s nothing speaking against confirming this on Thursday in the meeting.

Given that @mikeal indicated the space might be available to us without cost, and the idea was to bring in collaborators on the TSC budget, I don’t think the TSC actually needs to ask the Board for anything?

And I agree that it would still be good to have a good indication of how many @nodejs/collaborators (and maybe V8 people, @nodejs/v8) would be able to attend. You can still react to https://github.com/nodejs/summit/issues/39#issuecomment-281069507, fwiw.

**Comment by nebrius** [comment] 2017-03-08 01:12
+1 to discussing and finalizing at the next TSC meeting. I'm sure I speak for a lot of people when I say that the sooner this is finalized, the more time we have to arrange travel and go through the necessary steps of getting it approved.

**Comment by nebrius** [comment] 2017-03-09 23:09
Following up: we officially confirmed May 4th + 5th for the summit, so everyone feel free to start booking travel!

**Comment by nebrius** [comment] 2017-03-09 23:09
Also, count me in as an attendee. I'm confirmed going.

**Comment by fhinkel** [comment] 2017-03-10 07:06
I'll be there, too.

**Comment by yosuke-furukawa** [comment] 2017-03-10 12:20
I am looking forward to this summit. I will be Berlin in 4th and 5th May. But I concerned about the start time, according to my current flight schedule, I will be Berlin at 7:00 PM 4th May... but I can arrange this schedule flexible.

**Comment by ChALkeR** [comment] 2017-03-10 12:33
@nebrius Is the exact schedule (like the start time and end time) available? What is the exact location (is it Arena Berlin)?

**Comment by jasnell** [comment] 2017-03-10 16:05
I will definitely be there as well.

**Comment by nebrius** [comment] 2017-03-10 16:30
@ChALkeR the venue is still being secured (paging @mikeal), and the schedule is still to be determined. I would plan on each day being a typical full day, probably 9am-ish to 5pm-ish.

**Comment by watilde** [comment] 2017-03-10 16:49
\o I will be there

**Comment by MylesBorins** [comment] 2017-03-10 22:20
o/ see you there

**Comment by joyeecheung** [comment] 2017-03-11 02:22
\o Plan to be there as well

**Comment by mcollina** [comment] 2017-03-11 16:58
I will be at the collaborator summit!

**Comment by mikeal** [comment] 2017-03-11 17:51
Once we lock in the venue details we should add to http://wwwtf.berlin/

**Comment by robertkowalski** [comment] 2017-03-20 10:43
i'll join you! :) 🎉

**Comment by jbergstroem** [comment] 2017-03-20 17:05
Sorry to say this, but I won't be able to make it after all :( (just removed my above participation)

**Comment by Qard** [comment] 2017-03-20 17:58
I'm going to sit this one out. I'd love to go, but I can't afford it and I can't really justify asking for assistance again with how uninvolved I've been lately... 😞

**Comment by hackygolucky** [comment] 2017-03-23 15:58
It would be rad for us to get a schedule set up similar to what we did in Austin(our team set up a spreadsheet and @williamkapke had fun getting it up on screen and shared with everyone), with the spreadsheet of times that various groups could schedule into ahead. I know some of this happens onsite at the beginning of Collab Summit, but any ahead of time scheduling is usually helpful for people to maximize attending the most sessions!

**Comment by williamkapke** [comment] 2017-03-23 16:17
Indeed @hackygolucky! Many people ended up looking at that TV to figure out what was happening & where. It was a fairly low-tech solution, but I think it worked fine.

Here's the previous schedule BTW: https://github.com/nodejs/summit/issues/38

@Qard, the TSC has a travel fund you (and everyone else!) should ask about. We have the money set aside for this- we should use it!

**Comment by jasnell** [comment] 2017-03-23 17:11
Depending on what WG's we have represented at the event, it would be excellent to have a structured plenary session with a 20-30 minute presentation and discussion from each WG to update everyone on recent activities, current objectives, etc. Then, of course, open time for each of the WG's to get together. The structured plenary could come at the end of the collaborator summit event so if the WG's want, they could present what was discussed / planned at the summit itself.

Rough sketch schedule:

Day 1:  Morning: 
  Opening Breakfast / Introduction (30 minutes)
  WG Sessions
  Lunch
  WG Sessions

Day 2: Morning
  Opening Breakfast
  WG Sessions
  Lunch
  TSC/CTC Panel (TSC/CTC members fielding questions and discussion from collaborators)
  WG Presentations

The WG Sessions would be unconference open schedule type things kind of like what we did in Austin.

**Comment by jasnell** [comment] 2017-03-23 17:13
Thinking about it further, it would be beneficial during the plenary session to include an update presentation from @mikeal or @hackygolucky  about what is happening on the Foundation side of things along with an update on the Community Committee.

**Comment by hackygolucky** [comment] 2017-03-23 19:16
@jasnell Cool. Sounds good to me.

**Comment by Qard** [comment] 2017-03-23 19:20
@williamkapke Yeah, I used it for Austin. I don't really like asking for foundation money when there's probably plenty of other people more in need or more deserving of that money than I though. It'd also be quite an expensive trip from Vancouver to Berlin!

I'd love to be more involved again, but I've just been doing contract work for awhile and it's not awarding me the time and financial ability to be as involved as I'd like in the community. 😔

**Comment by nebrius** [comment] 2017-03-23 20:09
How about having a quick plenary at the beginning for all WGs to give a quick intro and mentioned what needs to be worked on (I'm thinking 2 minutes each)? I think this could help people decide which sessions to sit on in the case that they want to be in more than one. Then at the end, we could have the longer plenary to discuss what was accomplished and what the next steps are.

**Comment by targos** [comment] 2017-03-26 14:38
Is it confirmed that the summit will take place at co.up? Trying to find a hotel nearby...

**Comment by addaleax** [comment] 2017-03-26 22:26
@targos I’d say that’s a reasonable assumption to make. The funds should get approved in tomorrows board meeting, that’s the only thing we’re waiting for.

**Comment by piccoloaiutante** [comment] 2017-03-27 10:50
excellent going to be there

**Comment by calvinmetcalf** [comment] 2017-03-27 13:10
I can be there pending funding, talking to my work to see if they can cover all or (more likely) some of the cost and will put in a funding request based on that.

**Comment by fhemberger** [comment] 2017-03-27 13:23
Anyone attending interested in discussing some website issues?
(Updating foundation/TSC/governance stuff, events, discussing possible redesign topics, translations, etc)

**Comment by mhdawson** [comment] 2017-03-27 20:06
I'm going to try and make it.

**Comment by mikeal** [comment] 2017-03-28 01:18
Funding was approved in today's Board Meeting :)

**Comment by mikeal** [comment] 2017-03-28 01:19
Funding for the Berlin venue was approved in today's board meeting.

**Comment by sam-github** [comment] 2017-04-04 18:46
Can someone modify the description to include up-to-date date/time/venue information? I'm trawling the thread, trying to confirm its Thursday/Friday May 4th and 5th.

**Comment by danielkhan** [comment] 2017-04-05 13:40
Is the venue fixed already?

**Comment by sam-github** [comment] 2017-04-05 17:38
Don't know... makes it hard to book hotels.

**Comment by addaleax** [comment] 2017-04-05 17:42
Yes, this will be happening at http://co-up.de/ ([google maps](https://www.google.com/maps?hl=en&q=co-up+berlin)).

**Comment by sam-github** [comment] 2017-04-05 17:46
Thanks @addaleax - I don't have edit rights, do you? could you add that to the issue description?

**Comment by addaleax** [comment] 2017-04-05 17:48
@sam-github Done. Does anybody here mind if I give the collaborators team write access here? It only seems reasonable to do that…

**Comment by sam-github** [comment] 2017-04-05 17:49
Yes, given that its a collaborators summit, seems like collaborators should have write access.

**Comment by hackygolucky** [comment] 2017-04-11 19:05
Is this the planning issue or #41? I'm wondering which is a better place for everyone to be going for further details as we're all helping out.

**Comment by addaleax** [comment] 2017-04-11 19:07
I’ll just close this out, this thread is simply too long for newcomers to oversee. Let’s move things to #41.

**Closed by addaleax** 2017-04-11 19:07 UTC
Labels: Berlin 2017, tsc-agenda
