### ISSUE TITLE
Meeting Goals (Aug 2015)

### ISSUE THREAD

**Issue by groundwater** [nodejs/summit#6] opened 2015-07-21 22:39 UTC
I would like to (if possible) go into each meeting with a list of prioritized goals. I think @mikeal has volunteered to help drive an online consensus of those goals. There are six total meetings, but I think our final meeting should be "future goals".

So @mikeal I wonder if you can drive a process here, or in another thread to come up with five meeting plans. This process is free to change as it needs to, but I would like each plan to contain the following:

1. A general or specific list of prioritized goals. Shorter descriptions are better.
2. A description of documents the meeting intends to produce. Remember given the time constraints, this document will likely not exceed one page. If you want to produce multiple documents, please prioritize them.
3. A list of topics off-limits for *that* meeting, this includes topics to be discussed in other meetings.

Given the above, the facilitators will try their best to drive each meeting towards the outcomes listed in the plans. Keep in mind, the group is free to alter course as they see fit. The facilitators role is not to forbid discussion, but to coordinate discussion. A meeting plan is just the starting point for any meeting, but without a plan it would likely take the entire time to just agree on meeting goals.

**Comment by williamkapke** [comment] 2016-07-29 18:59
Much of this will need to be done for the upcoming summits. We may want to open another thread for them. Closing this since it was intended for the Aug 2015 summit.

**Closed by williamkapke** 2016-07-29 18:59 UTC
